training: !!bool "true"
experiment_name: "gradcam_BS64"
---
data:
    
---   
model:
    snapshot_path: "/content/drive/My Drive/EVA4/Session9/saves" 
---
train:
    shuffle: !!bool "true"
    loader_workers: 2
    batch_size: 32
    epochs: 31
    lr: 0.001
---
val:
    shuffle: !!bool "false"
    loader_workers: 2
    batch_size: 32    