training: !!bool "true"
experiment_name: "Xvec_transformer_001lr_withinfer_100seqlen_128batchlen"
---
data:

---   
model:
    ResNet_variant: ""
---
train:
    scheduler: "None"
    loader_workers: 3
    batch_size: 128
    epochs: 100
    lr: 0.001
---


